type SidebarSection =
  | "dashboard"
  | "student"
  | "add-student"
  | "view-student"
  | "student-profile"
  | "student-history"
  | "student-list"
  | "class"
  | "view-class"
  | "edit-class"
  | "add-class"
  | "employees"
  | "add-employee"
  | "edit-employee"
  | "view-employees"
  | "wallet"
  | "remit-payment"
  | "salary"
  | "generate"
  | "income"
  | "monthly-income"
  | "annual-income"
  | "message"
  | "expenses"
  | "analytics"
  | "settings";

export type { SidebarSection }